### ISSUE TITLE
크롬에서 기존글자 앞에 커서가 있을 때 사라지는 현상이 있습니다.

### ISSUE THREAD

**Issue by 1ocate** [navilera/NavilIMEforMac#1]
안녕하세요 좋은 입력기 만들어주셔서 감사합니다.

이게 버그인지 기능인지는 모르겠습니다만  크롬에서 텍스트 박스에 입력할 때

기존글자가 있으면 사라지는 현상이 있어서 피드백 드립니다.

사파리나, 기존 앱에서는 문제가 발생하지 않는 것 같습니다.

현재 제가 사용하는 환경 정보는 다음과 같습니다.

몬터레이 12.6.1
크롬 107.0.5304.110
NavilIME 3.2

동영상 첨부 합니다.

https://user-images.githubusercontent.com/29521447/204132524-71c5a5d6-de03-4df2-ab8e-c7229f9a823d.mov

**Comment by navilera** [comment]
크롬을 비롯해 일렉트론을 쓰는 모든 앱 (슬랙, vscode 등)에서 모두 동일하게 보이는 증상입니다. 크롬이 한글 처리를 이상하게 해서 생기는 현상입니다. 사실 저거는 크롬이 해결해 줘야 하는 문제입니다. 입력기는 정말 노말하게 동작하고 있거든요.... 아마도 기본 입력기의 버그를 회피하려고 크롬에서 이상하게 처리하는게 문제를 만드는 것으로 보입니다. 현재로써는 글자 중간에 내용을 넣을 때 공백을 하나 넣고 입력해서 회피하는 방법밖에는 없습니다.
해결방법을 찾는 중입니다. 이슈 레포팅 감사합니다.

**Comment by navilera** [comment]
4.5 버전에서 해결 했습니다.

**Comment by 1ocate** [comment]
안녕하세요 확인 했습니다.
너무 좋네요! 고생하셨습니다.
