### ISSUE TITLE
제3국어 키보드 사용 후 기호 문제(다른 문제)

### ISSUE THREAD

**Issue by lokumsoft** [navilera/NavilIMEforMac#14]
이전에 제3국어 사용 후, 기호가 이전 제3국어를 따라 가는 문제를 리포트 했고, 수정해주셨습니다.

그런데, 설명하기 약간 까다로운, 하지만 존재하는 오동작에 대해서 리포트를 드리려 합니다.

이전과 비슷한 문제이긴 한데요.

제3국어를 사용하고 나빌 입력기를 사용할 때, 현재는 문자 입력은 제대로 됩니다.

하지만 단축키를 사용할 때는 여전히 나빌 입력기가 이전 제3국어의 배열을 그대로 가지고 있는 것으로 보입니다.

이해를 돕기 위해 파일을 첨부합니다.

![IMG_2351](https://user-images.githubusercontent.com/51281537/229700298-64fa4e0c-daa0-4c39-bbf9-20549c5d1155.jpg)
이 캡춰 화면은 직전에 영문 자판을 사용하고 난 다음에 나빌 입력기로 돌아왔을 때의 키 배열입니다.

![IMG_2352](https://user-images.githubusercontent.com/51281537/229700513-f5b1b43c-07ee-40cf-8649-714da7b7e63d.jpg)
이 캡춰 화면은 직전에 제3국어(터키어)를 사용하고 난 다음에 나빌 입력기로 돌아왔을 때의 키 배열입니다. 배열이 터키어 자판과 동일합니다.

문제는 자판 배열은 저런데, 막상 누르면 한글 자판의 기호배열대로 입력이 됩니다. 그런데 단축키를 사용하기 위해서 cmd 등 다른 보조키와 누르면 캡춰 화면과 같이 제3국어 배열로 입력이 됩니다.

저는 무슨 문제인지 감도 안 오지만, 개발자님이 보시면 아실 수도 있어서 리포트해 봅니다. 혹시 수정이 가능할까요?

**Comment by navilera** [comment]
"키보드 뷰어보기"에 나오는 그림은 따로 그려서 넣어야 하는데, 해당 API가 뭔지 모르고 (공개된 API인지도 확실치 않습니다.)
그릴 수 있는 그림 실력도 되지 않아 넣지 않았습니다. 그래서 나빌 입력기 사용시 "키보드 뷰어보기"에 나오는 키보드 배치는 나빌 입력기와 전혀 상관이 없습니다.
단축키 처리는 입력기에서 하이재킹하지 않습니다.
cmd+[ 같은 단축키를 쓰시는 건가요? 그런 단축키가 아니라면 사용에 별 문제가 없어 보이긴 합니다.

**Comment by lokumsoft** [comment]
> "키보드 뷰어보기"에 나오는 그림은 따로 그려서 넣어야 하는데, 해당 API가 뭔지 모르고 (공개된 API인지도 확실치 않습니다.)
> 그릴 수 있는 그림 실력도 되지 않아 넣지 않았습니다. 그래서 나빌 입력기 사용시 "키보드 뷰어보기"에 나오는 키보드 배치는 나빌 입력기와 전혀 상관이 없습니다.
> 단축키 처리는 입력기에서 하이재킹하지 않습니다.
> cmd+[ 같은 단축키를 쓰시는 건가요? 그런 단축키가 아니라면 사용에 별 문제가 없어 보이긴 합니다.

모든 단축키가 다 안 됩니다. 제가 많이 사용하는 단축키는 cmd+=(확대), cmd+-(축소)이긴 하지만, 포토샵, 로직 등 기타 앱에서도 단축키가 작동하질 않습니다. 당장 입력은 한글키보드 기호대로 입력이 되지만, 각종 단축키는 이전 제3국어의 키배열대로 입력이 되어, 모든 앱에서 단축키를 사용할 수가 없는 문제입니다. 예를 들어, 포토샵에서 브러시 확대/축소도 안 됩니다. ㅠㅠ

키보드 그림과 관련해서는 '영문'을 사용하고 나빌로 오면 영문 자판을 보여주는데, '터키어'를 사용하고 나빌로 오면 터키어 자판을 보여준다는 걸 말씀드린 거고요. 실제로 단순 입력이 아닌 것은 전부 저 키보드 배열대로 작동합니다.

**Comment by navilera** [comment]
> 모든 단축키가 다 안 됩니다. 제가 많이 사용하는 단축키는 cmd+=(확대), cmd+-(축소)이긴 하지만, 포토샵, 로직 등 기타 앱에서도 단축키가 작동하질 않습니다. 당장 입력은 한글키보드 기호대로 입력이 되지만, 각종 단축키는 이전 제3국어의 키배열대로 입력이 되어, 모든 앱에서 단축키를 사용할 수가 없는 문제입니다. 예를 들어, 포토샵에서 브러시 확대/축소도 안 됩니다. ㅠㅠ
> 
> 키보드 그림과 관련해서는 '영문'을 사용하고 나빌로 오면 영문 자판을 보여주는데, '터키어'를 사용하고 나빌로 오면 터키어 자판을 보여준다는 걸 말씀드린 거고요. 실제로 단순 입력이 아닌 것은 전부 저 키보드 배열대로 작동합니다.

cmd+c, cmd+v 등은 잘 동작할 겁니다. 
나빌입력기는 cmd, shift 등 modifier key와 같이 들어오는 입력은 처리하지 않습니다. 왜냐하면 애플에서 제공하는 입력기 API에는 modi-key와 함께 동작하는 API가 없기 때문입니다. (아니면 제가 못 찾았거나...)

문자열 A를 문자열 B로 바꾸는것이 입력기의 핵심 동작입니다. "문자열"을 처리하기 때문에 modi-key는 처리하지 않습니다.

modi-key와 들어오는 입력을 keycode를 따라가지 않고 자판을 따라가는 것은 맥OS의 문제입니다. 

keymapping을 처리해주는 다른 프로그램 (카라비너 같은..) 을 사용하는 것이 더 좋은 해결책으로 보입니다.

**Comment by lokumsoft** [comment]
> > 모든 단축키가 다 안 됩니다. 제가 많이 사용하는 단축키는 cmd+=(확대), cmd+-(축소)이긴 하지만, 포토샵, 로직 등 기타 앱에서도 단축키가 작동하질 않습니다. 당장 입력은 한글키보드 기호대로 입력이 되지만, 각종 단축키는 이전 제3국어의 키배열대로 입력이 되어, 모든 앱에서 단축키를 사용할 수가 없는 문제입니다. 예를 들어, 포토샵에서 브러시 확대/축소도 안 됩니다. ㅠㅠ
> > 키보드 그림과 관련해서는 '영문'을 사용하고 나빌로 오면 영문 자판을 보여주는데, '터키어'를 사용하고 나빌로 오면 터키어 자판을 보여준다는 걸 말씀드린 거고요. 실제로 단순 입력이 아닌 것은 전부 저 키보드 배열대로 작동합니다.
> 
> cmd+c, cmd+v 등은 잘 동작할 겁니다. 나빌입력기는 cmd, shift 등 modifier key와 같이 들어오는 입력은 처리하지 않습니다. 왜냐하면 애플에서 제공하는 입력기 API에는 modi-key와 함께 동작하는 API가 없기 때문입니다. (아니면 제가 못 찾았거나...)
> 
> 문자열 A를 문자열 B로 바꾸는것이 입력기의 핵심 동작입니다. "문자열"을 처리하기 때문에 modi-key는 처리하지 않습니다.
> 
> modi-key와 들어오는 입력을 keycode를 따라가지 않고 자판을 따라가는 것은 맥OS의 문제입니다.
> 
> keymapping을 처리해주는 다른 프로그램 (카라비너 같은..) 을 사용하는 것이 더 좋은 해결책으로 보입니다.

cmd+c, cmd+v는 영문과 터키어 키보드 상에서 c와 v의 위치가 같기 때문에 제대로 동작합니다. 다른 부분은 동작을 하지 않습니다.
어쨌든 해결 방법이 없다는 말씀이시군요. 아쉽네요.
감사합니다.
