### ISSUE TITLE
한글 입력시 풀어쓰기 되는 것...

### ISSUE THREAD

**Issue by Secrice** [navilera/NavilIMEforMac#15]
맥에서 한글 입력을 하다보면 모아쓰기가 풀어져버리는 문제가 종종 있습니다. 구름에도 동일한데 그냥 한번 여쭤봅니다.

일단 제일 간단하게 재현해볼 수 있는 곳은 사진 앱입니다. 공유된 사진에 코멘트를 입력하려고 하면

동해물과 백두산이 마르고 닳도록 -> 동매ㄹㅘ 백수ㄴㅣ 마고 닳로ㄱ

이렇게 입력이 됩니다.

또 한가지 특이한 것은 맥의 기본 한글 입력기는 text selection을 만들지 않는데, 구름이나 나빌IME같은 경우는 입력하는 글자에 text selection이 생깁니다. Notion 앱에서 텍스트를 선택하면(shift 누르고 화살표) 위에 팝업 메뉴가 뜨는데, 구름이나 NavilIme에서는 한글을 입력하기만 해도 입력 중에 팝업 메뉴가 계속 따라옵니다. 눈으로 보기에도 text selection이 있는데, cmd + c 해서 복사해보면 이게 또 복사는 안되고.. 표시되는것만 그런건지.. 여튼 그렇습니다.

혹시 봐주실 수 있으시면...
감사합니다.

https://user-images.githubusercontent.com/2404820/233276662-05888d70-6831-4628-b71d-aed6e146d361.mov

https://user-images.githubusercontent.com/2404820/233276686-171fc734-0077-4d7f-b1c5-5ed89cb98cb9.mov

**Comment by navilera** [comment]
1. 애플에서 공개한 API를 쓰면 현재 조합중인 글자에 edit area를 지정해야 합니다. 노션에서는 그걸 선택영역으로 인식하는 것이고요. 기본입력기에서 문제가 없는 것은 아마 기본입력기는 공개한 API가 아니라 비공개 API를 쓰기 때문이겠지요. 노션은 기본입력기의 behavior에만 맞춰서 개발한것 같고요.
2. 저거는 무슨 기능인가요? 사진 앱에서 이것저것 눌러봐도 해당 기능을 찾을 수가 없습니다.

**Comment by Secrice** [comment]
사진을 공유앨범에 공유하면 코멘트를 입력할 수 있습니다.

보관함 > 사진 선택 > 위에 공유 메뉴 > 공유앨범

**Comment by navilera** [comment]
감사합니다.
공유 앨범 코맨트에서 그냥 한글 자소를 잡아 먹어 버리네요...
이거는 입력기 문제가 아니라 사진 앱 버그로 보입니다.
기본 입력기에서 잘 되는건 사진앱이 당연히 기본 입력기에서만 테스트 했을 테고... 기본 입력기는 비공개 API를 썼을 테고요.
