### ISSUE TITLE
'No Shift' 입력 방식을 위해 '종성' 입력 방식이 궁금합니다.

### ISSUE THREAD

**Issue by chulw** [navilera/NavilIMEforMac#2]
안녕하세요. 올려주신 것 잘 쓰고 있습니다.
사실, 한글에서 'Shift'를 입력하지 않고 쓰는 게 참 편리한데, 올려주신 방식에서 '두벌식' 입력 때 '초성'은 됩니다. '종성'이 있습니다. 입력 때는 어떻게 하는 건지 잘 모르겠습니다. '두벌식' 중 '순아래 입력기'가 이 부분이 완전하게 처리되고 있습니다만, 나빌 입력기도 '종성'의 된소리 등 처리만 잘 되면 괜찮을 듯 해서 혹시 방법이 없나 여쭙고자 합니다

가령, '있습니다'를 연이어 입력하면 '잇씁니다'라 써지고 '갓씁니다' 이런 식으로 됩니다.

**Comment by navilera** [comment]
현재 두벌식은 직관적으로 생각할 수 있는 수준에서 no shift를 구현했습니다. 두벌식 순아래 자판의 오토마타 자료를 구할 수 있으면 해당 방식으로 고쳐 보겠습니다. (검색하면 금방 나오나요? ^^)
나빌입력기 두벌식 오토마타는 Automata/Keyboard002.swift 파일을 참고하시면 됩니다.

**Comment by navilera** [comment]
두벌식 순아래 자판에서 @chulw 님이 언급한 문제를 피하려고 초성 쌍자음을 중성을 두번 눌러서 입력 "깍"을 "ㄱ+ㅏ+ㅏ+ㄱ"으로 입력하는 방식은 도저히 받아들일 수 없네요. 초성을 입력하는데 왜 중성을 두번 타이핑해야 하는지.... 다른 방법을 찾아보겠습니다. 두벌식 순아래 자판의 오리지날 오토마타는 제가 참기 힘드네요..

**Comment by chulw** [comment]
네, 저도 '순아래' 입력이 이질적이라 이번에 나빌입력기 구현하신 거 보고 받아써보고 있는데, 전 순아래보다도 'No Shift' 입력기를 두벌식 키보드 배열에서 직관적으로 어떻게 되나 궁금해서 여쭤봤습니다. 초성은 되는데, 종성이 입력 안 되고 풀려서 여쭤봤습니다.

**Comment by navilera** [comment]
간단합니다.

```
        self.chosung_layout = [
            "Q":Chosung.SsBiep, "qq":Chosung.SsBiep,
            "W":Chosung.SsJiek, "ww":Chosung.SsJiek,
            "E":Chosung.SsDigek, "ee":Chosung.SsDigek,
            "R":Chosung.SsGiyuk, "rr":Chosung.SsGiyuk,
            "T":Chosung.SsSiot, "tt":Chosung.SsSiot,
```

초성에는 rr, ee, tt 처럼 두번 입력으로 쌍자음을 맵핑했는데...

```
self.jongsung_layout = [
            "r":Jongsung.Kiyeok,    
            "R":Jongsung.Ssangkiyeok,
```

종성에는 대문자(시프트 입력)만 맵핑했거든요.. :)
