### ISSUE TITLE
언어전환 후 오타 문제입니다.

### ISSUE THREAD

**Issue by lokumsoft** [navilera/NavilIMEforMac#7]
잘 사용하고 있습니다.

제가 겪는 이슈 중의 하나는 언어 전환 후에 타이핑을 하려고 하면, 일부 글자가 누락되거나 앞뒤 글자가 바뀌는 현상이 생깁니다.

이렇게 타이핑을 하다가 언어 전환을 하고 바로 'abc를 치면'이라고 타이핑하면 'acb ㄹ르 치면' <-- 이렇게 입력이 됩니다.

아니면 'ac ㄹ르'라고 입력이 되기도 합니다.

검토해주세요.

**Comment by navilera** [comment]
어떤 프로그램에서 해당 문제가 생기나요? 이게 프로그램마다 입력기에서 한글을 받아서 처리하는게 다르기도 하거든요.
이 댓글을 쓰면서 사파리에서 여러번 시도해 봤는데 해당 문제는 생기지 않습니다. 기본 프로그램인 텍스트 에디터나 메모에서도 재현이 안되고요.
재현 시나리오를 알려주세요.

**Comment by lokumsoft** [comment]
> 어떤 프로그램에서 해당 문제가 생기나요? 이게 프로그램마다 입력기에서 한글을 받아서 처리하는게 다르기도 하거든요.
> 이 댓글을 쓰면서 사파리에서 여러번 시도해 봤는데 해당 문제는 생기지 않습니다. 기본 프로그램인 텍스트 에디터나 메모에서도 재현이 안되고요.
> 재현 시나리오를 알려주세요.

재현 시나리오라는 게 따로 없이 일어나는데요. 저는 주로 사파리에서 경험했습니다. 나빌을 사용하면 capslock 언어전환이 되지 않아서 단축키로 지정을 했더니 더 심하게 일어나긴 하는데, capslock을 포기하고 그냥 사용해도 전환 후 입력한 일부 타이핑을 씹는 현상이 일어납니다.
그런데 이 글을 쓰면서 계속 테스트를 해보니, 지구본을 눌러서 언어를 전환하는 방식으로 할 때 일어나네요. ctrl+space로 전환을 하면 안 일어나네요. 입력기 문제같습니다.
다만, 제가 기본입력기를 쓸 때 capslock으로 전환하는 방식을 계속 썼는데 나빌에서는 그게 안 되다보니 지구본을 눌러서 전환하거나 단축키로 capslock에 강제 지정하다보니 나타난 것 같습니다. 
capslock으로 이전입력방식으로 전환하는 옵션을 살려주시면 될 것 같은데, 고려해주세요.

**Comment by navilera** [comment]
입력기 전환은 OS에서 처리하는 거라 입력기는 OS에서 activate를 전달해주면 그저 activated 될 뿐입니다.

즉, (지구본이든 capslock이든 ctrl+space든) 사용자 입력 -> OS가 입력기 전환 -> activate 전달 -> 입력기가 받아서 activate 실행

activate 실행 부터 입력기의 영역이죠. 입력기에서 따로 지구본이든 capslock 이든 할 수 있는 일이 없습니다. 그런 옵션이라는 것 자체가 입력기 API에 없어요...

MacOS에서 지구본이나 capslock으로 입력 전환 할 때, 전환 시점에 입력 내용 몇 개를 입력기로 전달하지 않고 씹어 버리는 것으로 보입니다. 조금더 조사를 해 봐야 겠군요. 레포팅 감사합니다.

**Comment by lokumsoft** [comment]
말씀하신 내용이 맞는데, 나빌 입력기를 설치하면 capslock으로 입력 전환을 알 수 없어 빠르게 전환할 수 있는 방법이 지구본 누르는 것 밖에 없어서요. 나빌 입력기를 설치할 때, capslock 전환 옵션이 사라져버리는 문제는 해결이 어려운 걸까요?

**Comment by navilera** [comment]
capslock 전환 옵션과 입력기 API (IMKit) 사이에 어떤 상관 관계가 있는지 문서 찾는 중입니다. 현재로써는 아무런 정보가 없네요.
해당 옵션이 기본 입력기 사용 할 때만 보이고 다른 서드파티 입력기 (구름 입력기 등)을 쓸 때는 안보이는 거라면 이건 그냥 애플에서 기본 입력기에게만 허락한 기능으로 보이고요. 다른 서드파티 입력기에서도 보이는데 나빌 입력기에서만 안보이는 거라면 나빌 입력기 문제가 맞으니 방법을 찾아봐야 겠지요. 아무튼 찾아보겠습니다. 감사합니다.

**Comment by navilera** [comment]
https://github.com/gureum/gureum/issues/788

구름 입력기의 이슈인데... capslock 한영전환은 기본 입력기만 되는 기능으로 보입니다..

**Comment by kty0113** [comment]
@lokumsoft 
저도 해당 문제로 고민을 했고 karabiner 는 다른 app 과 충돌이 있어서 사용을 안했습니다. 

https://www.clien.net/service/board/lecture/17400367

링크에 있는 방법을 이용해서 capslock 키를 f18 로 매핑을 했고 
f18 을 언어 변환에 할당해서 사용중입니다.
