### ISSUE TITLE
특정 웹사이트 글쓰기시 줄변환 후 문제

### ISSUE THREAD

**Issue by kty0113** [navilera/NavilIMEforMac#8]
사파리 웹 브라우져에서 clien.net 클리앙 사이트 글쓰기시에

한글로 글 쓴후 엔터를 쳐서 줄을 바꾸고 다시 글자를 작성하면 줄바꿈이 사라지고 이전줄로 올라가서 작성됩니다. 

사파리 - 기본입력기 : 정상
사파리 - NavillME : 오작동
크롬 - NavillME : 정상

**Comment by navilera** [comment]
클리앙에서 쓰고 있는 리치 텍스트 에디터가 사파리+나빌입력기와 만날 때 희안하게 html을 만들더군요.
문단 종료하는 \</p\> 테그를 안 만들어서 생기는 문제입니다. 
강제로 html 에디터로 가서 \</p\>를 한번 수동으로 만들어주면 그 이후로는 또 정상입니다....
이걸 입력기 수준에서 어떻게 대응해야 할지 방법을 찾는 중입니다.

**Comment by navilera** [comment]
나빌 입력기 외에 기본 입력기 포함 다른 입력기에서도 발생하는 문제입니다. 입력기 문제가 아니라 맥OS+사파리+froala_editor(클리앙이 쓰는 텍스트 에디터) 조합일 때 발생하는 문제로 에디터의 버그입니다.
